version: '3'
services:
   db:
    build:
     context: .
     dockerfile: mysql_dockerfile
    image: mysql:bitnami
    restart: always
    ports:
       - 3306:3306

   tomcat:
     build:
       context: .
       dockerfile: tomcat_dockerfile
     depends_on:
       - db
     image: tomcat:bitnami
     volumes:
          - ./foo:/opt/ehour/ 
     ports:
       - "8888:8080"
     links:
       - db:mysql
   
   seleniumhub:
        image: selenium/hub
        ports:
           - 4444:4444
  
   firefoxnode:
        image: selenium/node-firefox-debug
        environment:
           - HUB_PORT_4444_TCP_ADDR=hub
        ports:
           - 4577
        links:
            - seleniumhub:hub
   chromenode:
        image : selenium/node-chrome-debug
        environment:
           - HUB_PORT_4444_TCP_ADDR=hub
        ports:
            - 4578
        links:
            - seleniumhub:hub
