version: '3'

services:
   db:
    build:
     context: .
     dockerfile: mysql_dockerfile
    image: mysql:bitnami
    restart: always
    ports:
       - 3306:3306

   tomcat:
     build:
         context: .
         dockerfile: tomcat_dockerfile
     depends_on:
       - db
     image: tomcat:bitnami
     volumes:
          - ./foo:/opt/ehour/ 
          - tomcathome:/usr/local/tomcat/
     ports:
       - "8888:8080"
     links:
       - db:mysql
volumes:
     tomcathome:
         driver: local
